In [2]:
print ("Om Vakaraduntaaya Namah")

Om Vakaraduntaaya Namah


In [3]:
import pandas as pd
import numpy as np

In [8]:
! ls /home/nbuser/

anaconda2_501  anaconda3_501  library  test_boston_gd.csv
anaconda3_420  IfSharp	      R        train_boston_gd.csv


In [9]:
# /home/nbuser/result_boston_new.csv
# /home/nbuser/test_boston_gd.csv/home/nbuser/train_boston_gd.csv
# /home/nbuser/train_boston_gd.csv
train_data = pd.read_csv('/home/nbuser/train_boston_gd.csv',delimiter = ',')
test_data = pd.read_csv('/home/nbuser/test_boston_gd.csv',delimiter = ',')
train_data.isnull().sum()

# CRIM      0
 ZN         0
 INDUS      0
 CHAS       0
 NOX        0
 RM         0
 AGE        0
 DIS        0
 RAD        0
 TAX        0
 PTRATIO    0
 B          0
 LSTAT      0
 Y          0
dtype: int64

In [10]:
# y_train = train_data.iloc[:,13:14]
Y = train_data[' Y']
del train_data[' Y']

In [11]:
last = np.zeros(train_data.shape[0])
train_data['last'] = last
train_data.head(2)

# CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1 -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  last  
0 -0.520264 -0.752922 -1.278354 -0.303094  0.410571 -1.097990   0.0  
1  0.336351 -0.523001 -0.060801  0.113032  0.291169 -0.520474   0.0

In [12]:
points = np.array(train_data)
points.shape

(379, 14)

In [48]:
len(points)

379

In [49]:
train_data.shape[0]

379

In [66]:
def step_gradient(points, learning_rate, m):
    m_slope = np.zeros(14)
    M = len(points)
    for i in range(M):
        x = points[i]   # no of rows 
        y = Y[i] 
        for j in range(14):
            m_slope[j] = m_slope[j]+(-2/M)* (y - (m * x).sum() )*x[j] # #Updating the weight and bias derivatives
  # update rule          
    for j in range(14):
        m[j] = m[j] - learning_rate*m_slope[j]
    
    return m

In [67]:
def gd(points, learning_rate, num_iterations):
    m=np.zeros(14)
    for i in range(num_iterations):
        m = step_gradient(points, learning_rate, m)
        print(i, " Cost: ", cost(points, m))
    return m

In [68]:
def cost(points, m):
    total_cost = 0
    M = len(points)
    for i in range(M):
        x = points[i]
        y = Y[i]
        total_cost += (1/M)*((y - (m*x).sum() )**2)     # cost = (1/N) * ∑(yi − y_train)2 {i from 1 to n}
    return total_cost

In [69]:
def run():
    learning_rate = 0.001  # defining the hyperparameters
    num_iterations = 1000  # defining the hyperparameters
    m = gd(points, learning_rate, num_iterations)
    print(m)
    return m

In [71]:
m=run()

0  Cost:  598.3388966495456
1  Cost:  597.5709116510045
2  Cost:  596.8179538126806
3  Cost:  596.0796716160776
4  Cost:  595.3557221281584
5  Cost:  594.6457707896772
6  Cost:  593.9494912087463
7  Cost:  593.2665649594985
8  Cost:  592.5966813857185
9  Cost:  591.9395374093383
10  Cost:  591.29483734365
11  Cost:  590.6622927111356
12  Cost:  590.0416220658061
13  Cost:  589.4325508199164
14  Cost:  588.8348110749673
15  Cost:  588.2481414568826
16  Cost:  587.6722869552522
17  Cost:  587.1069987665547
18  Cost:  586.5520341412413
19  Cost:  586.0071562346066
20  Cost:  585.4721339613354
21  Cost:  584.9467418536489
22  Cost:  584.4307599229473
23  Cost:  583.9239735248764
24  Cost:  583.4261732277198
25  Cost:  582.9371546840516
26  Cost:  582.456718505542
27  Cost:  581.9846701408767
28  Cost:  581.5208197566722
29  Cost:  581.0649821213417
30  Cost:  580.6169764918301
31  Cost:  580.1766265031348
32  Cost:  579.7437600605742
33  Cost:  579.318209234693
34  Cost:  578.8998101587835

280  Cost:  545.090882274847
281  Cost:  545.0403219031383
282  Cost:  544.9900159366803
283  Cost:  544.9399628418203
284  Cost:  544.8901610989651
285  Cost:  544.8406092023513
286  Cost:  544.791305659828
287  Cost:  544.7422489926431
288  Cost:  544.6934377352281
289  Cost:  544.6448704350004
290  Cost:  544.5965456521519
291  Cost:  544.548461959461
292  Cost:  544.5006179420941
293  Cost:  544.4530121974232
294  Cost:  544.4056433348327
295  Cost:  544.3585099755469
296  Cost:  544.3116107524498
297  Cost:  544.2649443099111
298  Cost:  544.2185093036203
299  Cost:  544.1723044004161
300  Cost:  544.1263282781306
301  Cost:  544.0805796254258
302  Cost:  544.035057141639
303  Cost:  543.9897595366306
304  Cost:  543.9446855306376
305  Cost:  543.8998338541243
306  Cost:  543.8552032476397
307  Cost:  543.810792461682
308  Cost:  543.7666002565559
309  Cost:  543.7226254022407
310  Cost:  543.6788666782593
311  Cost:  543.6353228735491
312  Cost:  543.5919927863366
313  Cost:  543

555  Cost:  537.365222002049
556  Cost:  537.3513586171536
557  Cost:  537.3375569429224
558  Cost:  537.3238166799179
559  Cost:  537.3101375302143
560  Cost:  537.2965191973886
561  Cost:  537.2829613865092
562  Cost:  537.2694638041341
563  Cost:  537.2560261582962
564  Cost:  537.2426481585018
565  Cost:  537.2293295157193
566  Cost:  537.2160699423721
567  Cost:  537.2028691523321
568  Cost:  537.1897268609112
569  Cost:  537.1766427848547
570  Cost:  537.1636166423309
571  Cost:  537.1506481529277
572  Cost:  537.1377370376433
573  Cost:  537.1248830188782
574  Cost:  537.1120858204289
575  Cost:  537.0993451674815
576  Cost:  537.0866607866002
577  Cost:  537.074032405727
578  Cost:  537.0614597541679
579  Cost:  537.0489425625902
580  Cost:  537.0364805630129
581  Cost:  537.0240734888018
582  Cost:  537.0117210746603
583  Cost:  536.9994230566227
584  Cost:  536.9871791720509
585  Cost:  536.9749891596232
586  Cost:  536.9628527593272
587  Cost:  536.950769712457
588  Cost:  5

832  Cost:  535.1146883468091
833  Cost:  535.110315848879
834  Cost:  535.1059600039152
835  Cost:  535.1016207358604
836  Cost:  535.0972979690233
837  Cost:  535.0929916280796
838  Cost:  535.0887016380702
839  Cost:  535.0844279243945
840  Cost:  535.0801704128165
841  Cost:  535.0759290294565
842  Cost:  535.0717037007923
843  Cost:  535.0674943536551
844  Cost:  535.0633009152309
845  Cost:  535.0591233130582
846  Cost:  535.0549614750229
847  Cost:  535.0508153293591
848  Cost:  535.0466848046491
849  Cost:  535.0425698298183
850  Cost:  535.0384703341352
851  Cost:  535.0343862472092
852  Cost:  535.0303174989891
853  Cost:  535.0262640197616
854  Cost:  535.0222257401495
855  Cost:  535.0182025911089
856  Cost:  535.0141945039308
857  Cost:  535.0102014102349
858  Cost:  535.0062232419727
859  Cost:  535.002259931421
860  Cost:  534.9983114111834
861  Cost:  534.9943776141889
862  Cost:  534.9904584736893
863  Cost:  534.9865539232558
864  Cost:  534.9826638967821
865  Cost:  

In [72]:
#  new coeff
m

array([-0.71780834,  0.55595632, -0.09389334,  1.417138  , -0.46624404,
        3.98147951,  0.50962767, -0.55342928,  0.85458506,  0.07895533,
       -1.49892369,  0.6743183 , -3.03189895,  0.        ])

In [54]:
m

array([-0.71780834,  0.55595632, -0.09389334,  1.417138  , -0.46624404,
        3.98147951,  0.50962767, -0.55342928,  0.85458506,  0.07895533,
       -1.49892369,  0.6743183 , -3.03189895,  0.        ])

In [73]:
test_data[1] = np.ones(test_data.shape[0])

In [74]:
y_test = []
x1=np.array(test_data)
M = x1.shape[0]
for i in range(M):
    x = x1[i]
    z=(m*x).sum()
    y_test.append(z)

In [75]:
add_row=test_data.columns
add_row
row=[]
for i in add_row:
    row.append(float(i))
row=np.array(row)
z=(row*m).sum()
z

-12.177819800543976

In [76]:
y_test.insert(0,z)

In [77]:
y_test=np.array(y_test)

In [81]:
y_test

array([-1.21778198e+01,  5.16130044e+00, -1.68629857e+00,  2.27519628e-02,
       -2.71646485e+00, -1.82923011e+01,  4.23729812e+00, -8.57886463e-01,
       -4.97526031e+00, -2.13701010e+00,  6.91472994e-01, -4.40762303e+00,
       -2.61422123e+00, -1.06817684e+00,  2.38830328e+01,  2.87530398e-01,
       -3.31068294e-01,  2.44387294e+00, -3.18490262e+00,  7.51072543e+00,
        6.15291624e-02,  8.15835560e-02,  9.61373259e+00,  1.27903218e+01,
        9.75744333e+00, -7.29384617e+00, -3.23923209e+00,  7.34391312e+00,
        2.97737204e+00,  1.18856582e+01, -4.86040804e+00,  9.24633622e-01,
        5.20169453e-01,  2.11886480e+00, -5.28375724e+00,  3.85001638e+00,
        1.69429078e+00, -2.61922402e+00,  9.94190107e-01, -9.60478033e+00,
       -1.76324758e+01,  4.08010204e+00,  5.86939766e+00, -9.65489622e-01,
       -1.39143007e+00, -2.03906060e+01,  1.83402329e+01,  2.83017400e+00,
        9.34697427e+00, -2.71958780e+00, -4.32079688e+00,  1.64842440e+01,
       -1.92774566e+00, -

In [82]:
np.savetxt('/home/nbuser/result_boston_new.csv', y_test, delimiter=',',fmt='%1.5f')

In [83]:
! ls -ltr

total 0
-rw-r--r-- 1 nbuser nbuser       0 May 24 08:37 README.md
-rw-r--r-- 1 nbuser nbuser    3698 May 24 08:39 HousingData.csv
-rw-r--r-- 1 nbuser nbuser     101 May 24 09:20 Ridge_coef (alpha=0.01).csv
-rw-r--r-- 1 nbuser nbuser  287946 May 24 11:37 LinearRegStudentDemo(1) (2).ipynb
-rw-r--r-- 1 nbuser nbuser  172225 May 31 10:52 pychurn.csv
-rw-r--r-- 1 nbuser nbuser  103827 Jun  4 07:32 smote.png
-rw-r--r-- 1 nbuser nbuser  726504 Jun  6 11:33 Handling Imbalanced Data.ipynb
-rw-r--r-- 1 nbuser nbuser   12435 Jun 10 08:09 housing.csv
-rw-r--r-- 1 nbuser nbuser  155868 Jun 13 10:28 boston_housing.ipynb
-rw-r--r-- 1 nbuser nbuser 2013547 Jun 14 11:19 Churn Analysis working.ipynb
-rw-r--r-- 1 nbuser nbuser 2102820 Jun 17 14:00 Churn Analysis Final fac.ipynb
-rw-r--r-- 1 nbuser nbuser   13930 Jun 18 15:52 marketBasket.ipynb
-rw-r--r-- 1 nbuser nbuser       0 Jun 19 17:20 result_boston_new.csv
-rw-r--r-- 1 nbuser nbuser   46767 Jun 19 17:59 boston_gd_n.ipynb


In [80]:
! cat result_boston_new.csv